## **Codificação de Variáveis Categóricas**

A **codificação de variáveis categórica**s é uma etapa no pré-processamento de dados que transforma atributos categóricos em representações numéricas que os algoritmos de Machine Learning conseguem processar.

O momento que a codificação deve ser feita é **após a divisão dos dados em conjuntos de treinamento e teste**. Isso evita vazamento de dados, que ocorre quando informações fora do conjunto de treinamento são usadas para criar o modelo.

A divisão treino/teste deve sempre ser respeitada, e **apenas os dados de treinamento devem ser usados para ajustar (fit) o codificador**.

In [12]:
import pandas as pd

### **One-Hot Encoding**

Essa técnica transforma cada categoria de uma variável em uma nova coluna binária (0 ou 1). Cada uma dessas novas colunas indica a presença ou ausência da categoria correspondente na instância de dados original. Normalmente é utilizada para variáveis categóricas **nominais**.

A codificação One-Hot pode aumentar muito a dimensionalidade do conjunto de dados se a variável em questão tiver muitas categorias únicas.

A multicolinearidade pode ser um problema, já que as variáveis codificadas estão altamente correlacionadas. Um solução pode ser remover uma das colunas codificadas.

In [13]:
from category_encoders import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

df = pd.DataFrame({
    'animal': ['cachorro', 'elefante', 'galinha', 'leao', 'ser humano', 'cachorro', 'gato', 'ser humano', 'elefante', 'pardal', 'macaco', 'cachorro'],
    'locomocao' : ['quadrupede', 'quadrupede','bipede',  'quadrupede', 'bipede',  'quadrupede',  'quadrupede', 'bipede', 'quadrupede', 'bipede', 'bipede', 'quadrupede'],
    'target': [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0]
})

X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='target'), df['target'])

encoder = OneHotEncoder(cols=['animal', 'locomocao'])

encoder.fit(X_train)

X_train_encoded = encoder.transform(X_train)
X_test_encoded = encoder.transform(X_test)

display(X_train_encoded)

,animal_1,animal_2,animal_3,animal_4,animal_5,animal_6,animal_7,animal_8,locomocao_1,locomocao_2
8,1,0,0,0,0,0,0,0,1,0
3,0,1,0,0,0,0,0,0,1,0
6,0,0,1,0,0,0,0,0,1,0
1,1,0,0,0,0,0,0,0,1,0
5,0,0,0,1,0,0,0,0,1,0
2,0,0,0,0,1,0,0,0,0,1
10,0,0,0,0,0,1,0,0,0,1
4,0,0,0,0,0,0,1,0,0,1
9,0,0,0,0,0,0,0,1,0,1

### **Label Encoding**

Esse técnica atribui a cada categoria única de uma variável categórica um número inteiro único. Normalmente é utilizada em variáveis categóricas **ordinais**.

A técnica de Label Encoding cria uma suposição implícita de que as categiras têm uma ordem ou hierarquia, que pode ou não existir.

In [14]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='target'), df['target'])

encoder = OrdinalEncoder(cols=['animal', 'locomocao'])

encoder.fit(X_train)

X_train_encoded = encoder.transform(X_train)
X_test_encoded = encoder.transform(X_test)

display(X_train_encoded)

    animal  locomocao
7        1          1
8        2          2
6        3          2
3        4          2
11       5          2
2        6          1
10       7          1
4        1          1
0        5          2