### **Exemplo - Exercício 10**

In [56]:
import pandas as pd

In [57]:
df = pd.read_csv("datasets/data_exemplo_com_nulos.csv").drop(columns='id')
display(df.head())
print(df.shape)

,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,Apple,8.0,256.0,8.0,4.0,2.71,4860.08
1,Acer,8.0,2048.0,4.0,0.0,2.30,NaN
2,NaN,8.0,512.0,16.0,8.0,NaN,7078.96
3,HP,16.0,NaN,8.0,6.0,2.50,8161.93
4,HP,8.0,256.0,12.0,0.0,3.15,4468.57

(30, 7)

In [58]:
mask_valores_nan = df.isna()
df_nan = df[mask_valores_nan.any(axis=1)]

display(df_nan)

,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
1,Acer,8.0,2048.0,4.0,0.0,2.30,NaN
2,NaN,8.0,512.0,16.0,8.0,NaN,7078.96
3,HP,16.0,NaN,8.0,6.0,2.50,8161.93
5,Acer,8.0,2048.0,NaN,0.0,5.11,7435.72
6,Lenovo,32.0,1024.0,16.0,4.0,NaN,8641.29
10,ASUS,16.0,1024.0,NaN,4.0,4.63,6054.83
11,Apple,32.0,256.0,6.0,NaN,4.80,8036.01
12,Acer,64.0,2048.0,12.0,4.0,NaN,11810.58
14,Apple,NaN,NaN,NaN,0.0,2.49,7572.19
18,HP,16.0,256.0,8.0,NaN,3.62,7668.55
20,NaN,32.0,512.0,4.0,4.0,4.81,6823.57
22,Acer,NaN,NaN,16.0,12.0,3.35,8970.88
24,NaN,64.0,256.0,6.0,NaN,2.20,NaN
28,Apple,NaN,1024.0,12.0,8.0,3.49,11735.25
29,Lenovo,8.0,256.0,12.0,16.0,3.09,NaN

In [59]:
qtd_values_nan = df.isna().sum()

print(f"Quantidade valores nulos:\n{qtd_values_nan}")

Quantidade valores nulos:
marca               3
ram_gb              3
armazenamento_gb    3
nucleos_cpu         3
vram_gpu_gb         3
clock_cpu_ghz       3
preco_rs            3
dtype: int64

#### **Exclusão de valores nulos**

A remoção dos valores nulos pode ser uma opção de tratamento quando:

- A proporção dos valores nulos é pequena, que sua remoção não impactaria de forma significativa no resultado final.
- A origem dos dados nulos é do tipo MCAR (Missing Completely at Random), que sua remoção não iria introduzir viés no modelo.

In [60]:
df_removed_nan = df.dropna()
display(df_removed_nan.head())
print(df_removed_nan.shape)

,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,Apple,8.0,256.0,8.0,4.0,2.71,4860.08
4,HP,8.0,256.0,12.0,0.0,3.15,4468.57
7,HP,32.0,256.0,6.0,0.0,3.22,5561.25
8,Apple,16.0,1024.0,8.0,4.0,4.14,6543.89
9,HP,8.0,512.0,16.0,16.0,2.78,8609.76

(15, 7)

#### **Imputação de valores**

A imputação de valores pode ser uma opção de tratamento quando:
- A proporção dos valores nulos é muito grande.
- A origem dos dados nulos é do tipo MAR (Missing at Random).

Obs: A imputação também pode ser feita por meio de algoritmos de Machine Learning.

In [61]:
df_imputed = df[['ram_gb', 'armazenamento_gb', 'nucleos_cpu', 'vram_gpu_gb', 'clock_cpu_ghz', 'preco_rs']].fillna(df[['ram_gb', 'armazenamento_gb', 'nucleos_cpu', 'vram_gpu_gb', 'clock_cpu_ghz', 'preco_rs']].mean())

df_imputed['marca'] = df['marca'].fillna(df['marca'].mode()[0])

display(df_imputed)

,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs,marca
0,8.000000,256.000000,8.000000,4.000000,2.710000,4860.080000,Apple
1,8.000000,2048.000000,4.000000,0.000000,2.300000,7906.765556,Acer
2,8.000000,512.000000,16.000000,8.000000,3.578889,7078.960000,HP
3,16.000000,805.925926,8.000000,6.000000,2.500000,8161.930000,HP
4,8.000000,256.000000,12.000000,0.000000,3.150000,4468.570000,HP
5,8.000000,2048.000000,10.518519,0.000000,5.110000,7435.720000,Acer
6,32.000000,1024.000000,16.000000,4.000000,3.578889,8641.290000,Lenovo
7,32.000000,256.000000,6.000000,0.000000,3.220000,5561.250000,HP
8,16.000000,1024.000000,8.000000,4.000000,4.140000,6543.890000,Apple
9,8.000000,512.000000,16.000000,16.000000,2.780000,8609.760000,HP
10,16.000000,1024.000000,10.518519,4.000000,4.630000,6054.830000,ASUS
11,32.000000,256.000000,6.000000,5.851852,4.800000,8036.010000,Apple
12,64.000000,2048.000000,12.000000,4.000000,3.578889,11810.580000,Acer
13,32.000000,2048.000000,16.000000,8.000000,3.160000,11132.000000,Lenovo
14,25.185185,805.925926,10.518519,0.000000,2.490000,7572.190000,Apple
15,64.000000,256.000000,12.000000,8.000000,3.910000,10699.030000,HP
16,8.000000,256.000000,16.000000,6.000000,4.460000,6397.310000,HP
17,64.000000,512.000000,12.000000,0.000000,5.050000,9764.910000,HP
18,16.000000,256.000000,8.000000,5.851852,3.620000,7668.550000,HP
19,16.000000,256.000000,16.000000,6.000000,3.560000,6810.320000,HP
20,32.000000,512.000000,4.000000,4.000000,4.810000,6823.570000,HP
21,64.000000,256.000000,16.000000,4.000000,2.410000,10353.370000,Acer
22,25.185185,805.925926,16.000000,12.000000,3.350000,8970.880000,Acer
23,16.000000,1024.000000,12.000000,16.000000,4.080000,9379.660000,Acer
24,64.000000,256.000000,6.000000,5.851852,2.200000,7906.765556,HP
25,16.000000,512.000000,4.000000,0.000000,4.270000,4156.720000,Dell
26,8.000000,1024.000000,4.000000,12.000000,2.760000,6746.190000,Lenovo
27,16.000000,2048.000000,6.000000,8.000000,4.580000,8009.850000,Dell
28,25.185185,1024.000000,12.000000,8.000000,3.490000,11735.250000,Apple
29,8.000000,256.000000,12.000000,16.000000,3.090000,7906.765556,Lenovo