### **Exemplo - Exercício 7**

In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'B': [5, 6], 'C': [7, 8]})
df3 = pd.DataFrame({'D': [9, 10]})

##### **Exemplo 1**

In [3]:
# Axis = 0 -> Linhas

resultado = pd.concat([df1, df2], axis=0)

display(resultado)

     A  B    C
0  1.0  3  NaN
1  2.0  4  NaN
0  NaN  5  7.0
1  NaN  6  8.0

##### **Exemplo 2**

In [4]:
# Axis = 1 -> Colunas

resultado = pd.concat([df1, df3], axis=1)

display(resultado)

   A  B   D
0  1  3   9
1  2  4  10

- No **Exemplo 1,** o **df1** e **df2** foram utilizados com o **axis = 0** e possuem colunas diferentes, logo os espaços foram preenchidos como **NaN**.

- No **Exemplo 2**, o **df1** e **df3** foram utilizados com **axis = 1** e possuem o mesmo número de linhas, logo não ocorre os valores **NaN**.