### **Exemplo - Exercício 9**

In [50]:
import pandas as pd

In [51]:
df = pd.read_csv('datasets/data_exemplo.csv')
display(df.head())

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,1,Apple,8,256,8,4,2.71,4860.08
1,2,Acer,8,2048,4,0,2.30,5267.20
2,3,Dell,8,512,16,8,2.71,7078.96
3,4,HP,16,2048,8,6,2.50,8161.93
4,5,HP,8,256,12,0,3.15,4468.57

#### **Selecionando colunas específicas**

In [52]:
series = df['marca']
display(series.head())

0    Apple
1     Acer
2     Dell
3       HP
4       HP
Name: marca, dtype: str

In [53]:
print(type(series))

<class 'pandas.Series'>

In [54]:
dataframe = df[['marca']]
display(dataframe.head())

   marca
0  Apple
1   Acer
2   Dell
3     HP
4     HP

In [55]:
print(type(dataframe))

<class 'pandas.DataFrame'>

In [56]:
df.nucleos_cpu.head()

0     8
1     4
2    16
3     8
4    12
Name: nucleos_cpu, dtype: int64

In [57]:
df[['ram_gb', 'marca']].head()

   ram_gb  marca
0       8  Apple
1       8   Acer
2       8   Dell
3      16     HP
4       8     HP

#### **Filtragem por condição**

In [58]:
df_result = df[df['nucleos_cpu'] > 10]
display(df_result)

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
2,3,Dell,8,512,16,8,2.71,7078.96
4,5,HP,8,256,12,0,3.15,4468.57
5,6,Acer,8,2048,16,0,5.11,7435.72
6,7,Lenovo,32,1024,16,4,4.25,8641.29
9,10,HP,8,512,16,16,2.78,8609.76
12,13,Acer,64,2048,12,4,2.85,11810.58
13,14,Lenovo,32,2048,16,8,3.16,11132.00
15,16,HP,64,256,12,8,3.91,10699.03
16,17,HP,8,256,16,6,4.46,6397.31
17,18,HP,64,512,12,0,5.05,9764.91
19,20,HP,16,256,16,6,3.56,6810.32
21,22,Acer,64,256,16,4,2.41,10353.37
22,23,Acer,16,1024,16,12,3.35,8970.88
23,24,Acer,16,1024,12,16,4.08,9379.66
28,29,Apple,64,1024,12,8,3.49,11735.25
29,30,Lenovo,8,256,12,16,3.09,7973.20

In [59]:
df_result = df.query("marca == 'HP'").reset_index(drop=True)
display(df_result)

,id,marca,ram_gb,armazenamento_gb,nucleos_cpu,vram_gpu_gb,clock_cpu_ghz,preco_rs
0,4,HP,16,2048,8,6,2.50,8161.93
1,5,HP,8,256,12,0,3.15,4468.57
2,8,HP,32,256,6,0,3.22,5561.25
3,10,HP,8,512,16,16,2.78,8609.76
4,16,HP,64,256,12,8,3.91,10699.03
5,17,HP,8,256,16,6,4.46,6397.31
6,18,HP,64,512,12,0,5.05,9764.91
7,19,HP,16,256,8,16,3.62,7668.55
8,20,HP,16,256,16,6,3.56,6810.32